import { useEffect, useState } from "react";
import { CheckCircle2, Download, KeyRound, Monitor, Network, RefreshCw, Router, ShieldCheck, Wifi, Link2Off } from "lucide-react";
import { confirm } from "@tauri-apps/plugin-dialog";
import { PageHeader } from "@/components/ui/PageHeader";
import { useAuthContext } from "@/stores/authContext";
import { backupService } from "@/services/backup";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { lanTransferService } from "@/services/lanTransfer";
import type { LanDevice, PairingRequest, PairingSession } from "@/types/lanTransfer";

export function LanTransferPage() {
  const [local,setLocal]=useState<LanDevice|null>(null),[devices,setDevices]=useState<LanDevice[]>([]),[paired,setPaired]=useState<LanDevice[]>([]),[requests,setRequests]=useState<PairingRequest[]>([]);
  const auth=useAuthContext(); const [scanning,setScanning]=useState(false),[error,setError]=useState(""),[session,setSession]=useState<PairingSession|null>(null),[code,setCode]=useState(""),[busy,setBusy]=useState(false),[backups,setBackups]=useState<Array<{id:number;file_path:string;file_size:number;created_at:string;backup_type:string}>>([]),[selectedBackup,setSelectedBackup]=useState<number|null>(null),[sending,setSending]=useState(false),[transferMessage,setTransferMessage]=useState(""),[selectedDevice,setSelectedDevice]=useState(""),[testingDevice,setTestingDevice]=useState(""),[history,setHistory]=useState<Array<{id:number;direction:string;file_name:string;file_size:number;status:string;created_at:string;device_name:string}>>([]);
  const refreshRequests=async()=>{try{setRequests(await lanTransferService.pairingRequests());}catch{}};
  const refreshPaired=async()=>{try{setPaired(await lanTransferService.pairedDevices());}catch{}};
  useEffect(()=>{void lanTransferService.getDevice().then(setLocal).catch(()=>undefined); if(auth.status?.is_authenticated){void backupService.list(auth.token ?? "").then(setBackups).catch(()=>undefined);} void refreshRequests(); void refreshPaired(); void lanTransferService.history().then(setHistory).catch(()=>undefined); const t=window.setInterval(()=>{void refreshRequests();void refreshPaired();},2000); return()=>window.clearInterval(t);},[]);
  const scan=async()=>{setScanning(true);setError("");try{setDevices(await lanTransferService.discover());}catch(e){setError(e instanceof Error?e.message:"Unable to scan the local network.");}finally{setScanning(false);}};
  const pair=async(d:LanDevice)=>{setBusy(true);setError("");try{setSession(await lanTransferService.requestPairing(d));}catch(e){setError(e instanceof Error?e.message:"Unable to request pairing.");}finally{setBusy(false);}};
  const approve=async(r:PairingRequest)=>{setBusy(true);setError("");try{await lanTransferService.approvePairing(r.device_id,code);setCode("");await refreshRequests();await refreshPaired();}catch(e){setError(e instanceof Error?e.message:"Pairing failed.");}finally{setBusy(false);}};
  const test=async(deviceId:string)=>{setTestingDevice(deviceId);setError("");try{await lanTransferService.testConnection(deviceId);setTransferMessage("Trusted device is online and authenticated.");await refreshPaired();}catch(e){setError(e instanceof Error?e.message:"Connection test failed.");}finally{setTestingDevice("");}};
  const revoke=async(deviceId:string)=>{if(!window.confirm("Remove this trusted device?"))return;setBusy(true);setError("");try{await lanTransferService.revokeDevice(deviceId);if(selectedDevice===deviceId)setSelectedDevice("");await refreshPaired();}catch(e){setError(e instanceof Error?e.message:"Unable to remove trusted device.");}finally{setBusy(false);}};
  const send=async()=>{if(selectedBackup===null||!selectedDevice)return;setSending(true);setTransferMessage("");try{await lanTransferService.sendBackup(selectedBackup,selectedDevice);setTransferMessage("Backup transferred and authenticated successfully.");}catch(e){setTransferMessage(e instanceof Error?e.message:"Transfer failed.");}finally{setSending(false);}};
  const importReceived=async(backup:{id:number;created_at:string})=>{setBusy(true);setError("");setTransferMessage("");try{const ok=await confirm(`Import this received LAN backup from ${new Date(backup.created_at).toLocaleString()}?\n\nA pre-import safety backup will be created first. If import or version upgrade fails, the original database will be restored automatically.`,{title:"Import LAN Backup",kind:"warning"});if(!ok){setBusy(false);return;}const res=await lanTransferService.importBackup(backup.id);if(res.success){setTransferMessage("LAN backup imported safely. The original database is preserved in the pre-import safety backup. Please sign in again.");window.setTimeout(()=>window.location.reload(),900);}else setError(res.message);}catch(e){setError(e instanceof Error?e.message:"Unable to import LAN backup.");}finally{setBusy(false);}};
  return <div className="pb-8"><PageHeader title="LAN Transfer" description="Securely discover and pair Payroll System devices on the same local network." />
    <div className="grid gap-4 lg:grid-cols-[1.05fr_.95fr]">
      <Card className="overflow-hidden"><div className="border-b border-[#292929] bg-[#111] px-5 py-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-white">This Device</p><p className="mt-1 text-[11px] text-[#70756f]">Identity used for secure pairing.</p></div><Monitor className="h-5 w-5 text-[#67b85a]"/></div></div><div className="p-5"><div className="rounded-2xl border border-[#292929] bg-[#101010] p-4"><p className="text-sm font-semibold text-white">{local?.device_name??"Loading…"}</p><p className="mt-1 break-all text-[10px] text-[#676c65]">{local?.device_id??"—"}</p><div className="mt-4 grid grid-cols-2 gap-3"><Info label="Version" value={local?.app_version??"—"}/><Info label="Protocol" value="LAN V2"/></div></div><div className="mt-4 flex gap-3 rounded-xl border border-[#252a24] bg-[#0d100d] p-3 text-[11px] leading-5 text-[#858b82]"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#67b85a]"/>Pairing requires an explicit approval and an 8-digit one-time code. Payroll data is not transferred during pairing.</div></div></Card>
      <Card className="overflow-hidden"><div className="border-b border-[#292929] bg-[#111] px-5 py-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-white">Discover Devices</p><p className="mt-1 text-[11px] text-[#70756f]">Find Payroll System devices on this LAN.</p></div><Router className="h-5 w-5 text-[#67b85a]"/></div></div><div className="p-5"><Button onClick={scan} disabled={scanning||busy} className="w-full py-3"><RefreshCw className={`h-4 w-4 ${scanning?"animate-spin":""}`}/>{scanning?"Scanning…":"Scan for Devices"}</Button>{error&&<div className="mt-3 rounded-xl border border-[#4b3028] bg-[#1b1210] p-3 text-[11px] text-[#d7a99b]">{error}</div>}<div className="mt-4 space-y-2">{devices.map(d=><div key={d.device_id} className="flex items-center gap-3 rounded-xl border border-[#292929] bg-[#101010] p-3"><Network className="h-4 w-4 text-[#67b85a]"/><div className="min-w-0 flex-1"><p className="truncate text-[12px] font-semibold text-white">{d.device_name}</p><p className="text-[10px] text-[#6e736c]">{d.ip_address} · v{d.app_version}</p></div><Button onClick={()=>void pair(d)} disabled={busy} className="px-3 py-2 text-[10px]">Pair</Button></div>)}{devices.length===0&&<div className="rounded-xl border border-dashed border-[#303030] p-6 text-center"><Wifi className="mx-auto h-7 w-7 text-[#555]"/><p className="mt-2 text-[12px] font-semibold text-[#b5b9b2]">No devices listed</p></div>}</div></div></Card>
    </div>
    {session&&<div className="mt-4"><Card className="border-[#30472d] bg-[#101510] p-5"><div className="flex items-start gap-3"><KeyRound className="mt-1 h-5 w-5 text-[#67b85a]"/><div className="flex-1"><p className="text-sm font-semibold text-white">Pairing code</p><p className="mt-1 text-[11px] text-[#8b9188]">Give this code to the administrator on {session.device_name}. It expires in {session.expires_seconds} seconds.</p><div className="my-4 rounded-xl border border-[#30472d] bg-[#0b0f0b] py-4 text-center text-2xl font-bold tracking-[0.35em] text-[#67b85a]">{session.code}</div><Button onClick={()=>setSession(null)} className="px-4 py-2">Close</Button></div></div></Card></div>}
    {requests.length>0&&<div className="mt-4"><Card className="overflow-hidden"><div className="border-b border-[#292929] bg-[#111] px-5 py-4"><p className="text-sm font-semibold text-white">Incoming Pairing Requests</p></div><div className="space-y-2 p-5">{requests.map(r=><div key={r.device_id} className="flex flex-wrap items-center gap-3 rounded-xl border border-[#292929] bg-[#101010] p-3"><div className="flex-1"><p className="text-[12px] font-semibold text-white">{r.device_name}</p><p className="text-[10px] text-[#6e736c]">{r.ip_address}</p></div><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,8))} placeholder="8-digit code" inputMode="numeric" className="w-32 rounded-lg border border-[#303030] bg-[#0b0b0b] px-3 py-2 text-center text-xs text-white outline-none focus:border-[#4a8b3f]"/><Button onClick={()=>void approve(r)} disabled={busy||code.length!==8} className="px-4 py-2">Approve</Button></div>)}</div></Card></div>}
    {paired.length>0&&<div className="mt-4"><Card className="overflow-hidden"><div className="border-b border-[#292929] bg-[#111] px-5 py-4"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#67b85a]"/><p className="text-sm font-semibold text-white">Secure Backup Transfer</p></div><p className="mt-1 text-[11px] text-[#70756f]">Send an existing encrypted backup to a trusted paired device.</p></div><div className="p-5"><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><select value={selectedDevice} onChange={e=>setSelectedDevice(e.target.value) } className="rounded-xl border border-[#303030] bg-[#0d0d0d] px-3 py-3 text-xs text-white outline-none focus:border-[#4a8b3f]"><option value="">Select trusted device</option>{paired.map(d=><option key={d.device_id} value={d.device_id}>{d.device_name} · {d.ip_address}</option>)}</select><select value={selectedBackup??""} onChange={e=>setSelectedBackup(e.target.value?Number(e.target.value):null)} className="rounded-xl border border-[#303030] bg-[#0d0d0d] px-3 py-3 text-xs text-white outline-none focus:border-[#4a8b3f]"><option value="">Select backup</option>{backups.map(b=><option key={b.id} value={b.id}>{b.backup_type} · {new Date(b.created_at).toLocaleString()}</option>)}</select><Button onClick={()=>void send()} disabled={sending||selectedBackup===null||!selectedDevice}>{sending?"Sending…":"Send Securely"}</Button></div>{transferMessage&&<div className="mt-3 rounded-xl border border-[#30472d] bg-[#0d100d] p-3 text-[11px] text-[#aeb8aa]">{transferMessage}</div>}<p className="mt-3 text-[10px] text-[#62675f]">Transfer is encrypted, authenticated against the paired device, checksum-verified, and recorded in transfer history.</p></div></Card></div>}
    {backups.some(b=>b.backup_type==="lan_received")&&<div className="mt-4"><Card className="overflow-hidden"><div className="border-b border-[#292929] bg-[#111] px-5 py-4"><div className="flex items-center gap-2"><Download className="h-4 w-4 text-[#67b85a]"/><div><p className="text-sm font-semibold text-white">Received LAN Backups</p><p className="mt-1 text-[11px] text-[#70756f]">Import a received backup with automatic pre-import protection and rollback.</p></div></div></div><div className="space-y-2 p-5">{backups.filter(b=>b.backup_type==="lan_received").map(b=><div key={b.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-[#292929] bg-[#101010] p-3"><Download className="h-4 w-4 text-[#67b85a]"/><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-semibold text-white">{b.file_path.split("/").pop()||"Received backup"}</p><p className="text-[10px] text-[#6e736c]">{new Date(b.created_at).toLocaleString()} · {Math.round(b.file_size/1024)} KB</p></div><Button onClick={()=>void importReceived(b)} disabled={busy||sending} className="px-3 py-2 text-[10px]">{busy?"Importing…":"Import Safely"}</Button></div>)}</div></Card></div>}
    <div className="mt-4"><Card className="overflow-hidden"><div className="border-b border-[#292929] bg-[#111] px-5 py-4"><div className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-[#67b85a]"/><div><p className="text-sm font-semibold text-white">Trusted Devices</p><p className="mt-1 text-[11px] text-[#70756f]">Only paired devices can transfer payroll backups.</p></div></div></div><div className="space-y-2 p-5">{paired.length===0?<div className="rounded-xl border border-dashed border-[#303030] p-5 text-center text-[11px] text-[#70756f]">No trusted devices yet.</div>:paired.map(d=><div key={d.device_id} className="flex flex-wrap items-center gap-3 rounded-xl border border-[#292929] bg-[#101010] p-3"><CheckCircle2 className="h-4 w-4 text-[#67b85a]"/><div className="min-w-0 flex-1"><p className="truncate text-[12px] font-semibold text-white">{d.device_name}</p><p className="text-[10px] text-[#6e736c]">{d.ip_address} · Trusted</p></div><Button onClick={()=>void test(d.device_id)} disabled={!!testingDevice||busy} className="px-3 py-2 text-[10px]">{testingDevice===d.device_id?"Testing…":"Test"}</Button><Button onClick={()=>void revoke(d.device_id)} disabled={!!testingDevice||busy} className="px-3 py-2 text-[10px]"><Link2Off className="h-3.5 w-3.5"/>Remove</Button></div>)}</div></Card></div>
    {history.length>0&&<div className="mt-4"><Card className="p-5"><p className="text-sm font-semibold text-white">Transfer History</p><div className="mt-3 space-y-2">{history.slice(0,10).map(h=><div key={h.id} className="flex items-center gap-3 rounded-xl border border-[#292929] bg-[#101010] p-3"><Network className="h-4 w-4 text-[#67b85a]"/><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-semibold text-white">{h.file_name}</p><p className="text-[10px] text-[#6e736c]">{h.direction} · {h.device_name} · {h.status}</p></div></div>)}</div></Card></div>}
  </div>;
}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-[#252525] bg-[#0d0d0d] px-3 py-2"><p className="text-[9px] uppercase tracking-wider text-[#5f645d]">{label}</p><p className="mt-1 text-[11px] font-semibold text-[#c7cbc4]">{value}</p></div>;}
