import { FormEvent, useEffect, useMemo, useState } from "react";
import { Bell, CalendarClock, CheckCircle2, Clock3, Pencil, Plus, RotateCcw, Trash2, X } from "lucide-react";
import { useAuthContext } from "@/stores/authContext";
import { reminderService } from "@/services/reminders";
import type { Reminder, ReminderRecurrence, ReminderType } from "@/types/reminders";
import { PageHeader } from "@/components/ui/PageHeader";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";

const types: {value:ReminderType; label:string}[] = [
  {value:"general",label:"General"},{value:"payroll",label:"Payroll"},{value:"leave",label:"Leave"},
  {value:"loan",label:"Loan / Advance"},{value:"backup",label:"Backup"},{value:"update",label:"Updates"},
];
const recurrences: {value:ReminderRecurrence; label:string}[] = [
  {value:"none",label:"Once"},{value:"daily",label:"Daily"},{value:"weekly",label:"Weekly"},{value:"monthly",label:"Monthly"},
];
const inputClass="w-full rounded-xl border border-[#303030] bg-[#101010] px-3 py-2.5 text-[12px] text-white outline-none focus:border-[#4a8b3f]";
const typeLabel=(t:ReminderType)=>types.find(x=>x.value===t)?.label ?? "General";
const formatDue=(value:unknown)=>{ const s=typeof value==="string"?value:""; if(!s)return "Not scheduled"; const normalized=s.includes("T")?s:s.replace(" ","T"); const d=new Date(/Z$|[+-]\d{2}:?\d{2}$/.test(normalized)?normalized:`${normalized}Z`); return Number.isNaN(d.getTime())?s:d.toLocaleString([], {dateStyle:"medium",timeStyle:"short"}); };
const toLocalInput=(d:Date)=>{ const p=(n:number)=>String(n).padStart(2,"0"); return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`; };

export function RemindersPage(){
 const auth=useAuthContext(), token=auth.token;
 const [items,setItems]=useState<Reminder[]>([]), [due,setDue]=useState<Reminder[]>([]), [busy,setBusy]=useState(""), [error,setError]=useState(""), [message,setMessage]=useState("");
 const [openForm,setOpenForm]=useState(false), [editing,setEditing]=useState<Reminder|null>(null);
 const load=async()=>{ if(!token)return; try{const [all,d]=await Promise.all([reminderService.list(token),reminderService.due(token)]);setItems(Array.isArray(all)?all.filter(Boolean):[]);setDue(Array.isArray(d)?d.filter(Boolean):[]);}catch(e){setItems([]);setDue([]);setError(e instanceof Error?e.message:"Unable to load reminders.");} };
 useEffect(()=>{void load(); const t=window.setInterval(()=>void load(),30000); return()=>window.clearInterval(t);},[token]);
 const pending=useMemo(()=>items.filter(x=>!x.is_completed),[items]);
 const emptyDraft=()=>({title:"",message:"",reminder_type:"general" as ReminderType,due_date:toLocalInput(new Date(Date.now()+3600000)),recurrence:"none" as ReminderRecurrence});
 const [draft,setDraft]=useState(emptyDraft());
 useEffect(()=>{if(openForm){setDraft(editing?{title:editing.title,message:editing.message??"",reminder_type:editing.reminder_type,due_date:(()=>{const d=new Date(editing.due_date);return Number.isNaN(d.getTime())?toLocalInput(new Date(Date.now()+3600000)):toLocalInput(d)})(),recurrence:editing.recurrence}:emptyDraft());}},[openForm,editing]);
 const save=async(e:FormEvent)=>{e.preventDefault();if(!token)return;setBusy("save");setError("");setMessage("");try{const due=new Date(draft.due_date);if(Number.isNaN(due.getTime()))throw new Error("Please choose a valid date and time.");await reminderService.save(token,{id:editing?.id,title:draft.title.trim(),message:draft.message?.trim()||null,reminderType:draft.reminder_type,dueDate:due.toISOString(),recurrence:draft.recurrence});setOpenForm(false);setEditing(null);setMessage("Reminder saved.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to save reminder.");}finally{setBusy("");}};
 const openNew=()=>{setError("");setMessage("");setEditing(null);setOpenForm(true);};
 const openEdit=(r:Reminder)=>{setError("");setMessage("");setEditing(r);setOpenForm(true);};
 const act=async(kind:string,r:Reminder)=>{if(!token)return;setBusy(`${kind}-${r.id}`);setError("");try{if(kind==="complete")await reminderService.complete(token,r.id);if(kind==="snooze")await reminderService.snooze(token,r.id,60);if(kind==="delete")await reminderService.remove(token,r.id);setMessage(kind==="snooze"?"Reminder snoozed for 1 hour.":kind==="delete"?"Reminder deleted.":"Reminder completed.");await load();}catch(e){setError(e instanceof Error?e.message:"Reminder action failed.");}finally{setBusy("");}};
 return <div>
  <PageHeader title="Reminders" description="Keep payroll, leave, loan, backup and system tasks on schedule." />
  {(error||message)&&<div className={`mb-5 rounded-xl border px-4 py-3 text-[12px] ${error?"border-[#493b2b] bg-[#19150f] text-[#e4c58d]":"border-[#29432a] bg-[#111811] text-[#9ed394]"}`}>{error||message}</div>}
  <div className="grid gap-4 md:grid-cols-4 mb-5">
   {[{label:"Pending",value:pending.length,icon:Clock3},{label:"Due now",value:due.length,icon:Bell},{label:"Completed",value:items.filter(x=>x.is_completed).length,icon:CheckCircle2},{label:"Recurring",value:items.filter(x=>x.recurrence!=="none").length,icon:RotateCcw}].map(x=><Card key={x.label} className="p-4"><div className="flex items-center justify-between"><div><p className="text-[11px] uppercase tracking-wider text-[#707070]">{x.label}</p><p className="mt-2 text-2xl font-semibold text-white">{x.value}</p></div><x.icon className="h-5 w-5 text-[#4a8b3f]"/></div></Card>)}
  </div>
  {due.length>0&&<Card className="mb-5 border-[#3a4a32] bg-[#111711] p-4"><div className="flex items-center gap-2 mb-3"><Bell className="h-4 w-4 text-[#67b85a]"/><p className="text-sm font-semibold text-white">Due reminders</p></div><div className="space-y-2">{due.map(r=><div key={r.id} className="flex items-center justify-between rounded-xl border border-[#263126] bg-[#0c0f0c] p-3"><div><p className="text-[12px] font-semibold text-white">{r.title}</p><p className="text-[11px] text-[#777]">{typeLabel(r.reminder_type)} · {formatDue(r.due_date)}</p></div><div className="flex gap-2"><Button variant="ghost" onClick={()=>void act("snooze",r)} disabled={busy!==""}>Snooze</Button><Button onClick={()=>void act("complete",r)} disabled={busy!==""}>Done</Button></div></div>)}</div></Card>}
  <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-[#292929] px-5 py-4"><div><h2 className="text-sm font-semibold text-white">Reminder schedule</h2><p className="mt-1 text-[11px] text-[#707070]">Create one-time or recurring reminders.</p></div><Button onClick={()=>{setEditing(null);setOpenForm(true)}}><Plus className="h-4 w-4"/> New reminder</Button></div>
   {items.length===0?<div className="p-12 text-center"><CalendarClock className="mx-auto h-8 w-8 text-[#4a8b3f]"/><p className="mt-3 text-sm text-white">No reminders yet</p><p className="mt-1 text-xs text-[#707070]">Create your first payroll or system reminder.</p></div>:<div className="divide-y divide-[#242424]">{items.map(r=><div key={r.id} className="flex items-center justify-between gap-4 px-5 py-4"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${r.is_completed?"bg-[#202020] text-[#707070]":"bg-[#183017] text-[#9ed394]"}`}>{typeLabel(r.reminder_type)}</span>{r.recurrence!=="none"&&<span className="text-[10px] text-[#707070]">↻ {r.recurrence}</span>}</div><p className={`mt-2 text-[13px] font-semibold ${r.is_completed?"text-[#666] line-through":"text-white"}`}>{r.title}</p>{r.message&&<p className="mt-1 truncate text-[11px] text-[#777]">{r.message}</p>}</div><div className="hidden min-w-[180px] text-right sm:block"><p className="text-[11px] text-[#8a8a8a]">{r.is_completed?"Completed":"Due"}</p><p className="mt-1 text-[11px] text-[#bdbdbd]">{formatDue(r.due_date)}</p></div><div className="flex gap-1">{!r.is_completed&&<Button variant="ghost" title="Complete" onClick={()=>void act("complete",r)}><CheckCircle2 className="h-4 w-4"/></Button>}<Button variant="ghost" title="Edit" onClick={()=>{setEditing(r);setOpenForm(true)}}><Pencil className="h-4 w-4"/></Button><Button variant="ghost" title="Delete" onClick={()=>void act("delete",r)}><Trash2 className="h-4 w-4"/></Button></div></div>)}</div>}
  </Card>
  {openForm&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><Card className="w-full max-w-lg p-5"><div className="flex items-center justify-between mb-5"><div><h2 className="text-base font-semibold text-white">{editing?"Edit reminder":"New reminder"}</h2><p className="text-[11px] text-[#707070]">Set when and how often it should appear.</p></div><button onClick={()=>setOpenForm(false)} className="text-[#777] hover:text-white"><X className="h-5 w-5"/></button></div><form onSubmit={save} className="space-y-4"><div><label className="text-[11px] text-[#999]">Title</label><input className={inputClass+" mt-1"} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} required/></div><div><label className="text-[11px] text-[#999]">Message</label><textarea className={inputClass+" mt-1 min-h-20"} value={draft.message??""} onChange={e=>setDraft({...draft,message:e.target.value})}/></div><div className="grid gap-3 sm:grid-cols-2"><div><label className="text-[11px] text-[#999]">Category</label><select className={inputClass+" mt-1"} value={draft.reminder_type} onChange={e=>setDraft({...draft,reminder_type:e.target.value as ReminderType})}>{types.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select></div><div><label className="text-[11px] text-[#999]">Repeat</label><select className={inputClass+" mt-1"} value={draft.recurrence} onChange={e=>setDraft({...draft,recurrence:e.target.value as ReminderRecurrence})}>{recurrences.map(r=><option key={r.value} value={r.value}>{r.label}</option>)}</select></div></div><div><label className="text-[11px] text-[#999]">Due date & time</label><input type="datetime-local" className={inputClass+" mt-1"} value={draft.due_date.slice(0,16)} onChange={e=>setDraft({...draft,due_date:e.target.value})} required/></div><div className="flex justify-end gap-2 pt-2"><Button type="button" variant="secondary" onClick={()=>setOpenForm(false)}>Cancel</Button><Button type="submit" disabled={busy==="save"}>{busy==="save"?"Saving…":editing?"Save changes":"Create reminder"}</Button></div></form></Card></div>}
 </div>
}
